name: haskell-katas
version: 0.1.0.0
github: kamirus/haskell-katas
license: MIT
author: kamirus
copyright: 2020 kamirus
extra-source-files:
  - README.md
description: >-
  Please see the README on GitHub at
  <https://github.com/kamirus/haskell-katas#readme>
dependencies:
  - base >= 4.7 && < 5
  - lens
  - hspec
library:
  source-dirs: src
# executables:
#   haskell-katas-exe:
#     main: Main.hs
#     source-dirs: app
#     ghc-options:
#       - '-threaded'
#       - '-rtsopts'
#       - '-with-rtsopts=-N'
#     dependencies:
#       - haskell-katas
tests:
  haskell-katas-test:
    main: SimpleLensSpec.hs
    source-dirs: test
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - haskell-katas
